// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WeatherServiceClientHW04.Models
{
    public partial class Humidity
    {
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _percentage;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Percentage
        {
            get { return this._percentage; }
            set { this._percentage = value; }
        }
        
        private DateTimeOffset _recorDateTime;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset RecorDateTime
        {
            get { return this._recorDateTime; }
            set { this._recorDateTime = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Humidity class.
        /// </summary>
        public Humidity()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the Humidity class with required
        /// arguments.
        /// </summary>
        public Humidity(string percentage, DateTimeOffset recorDateTime)
            : this()
        {
            if (percentage == null)
            {
                throw new ArgumentNullException("percentage");
            }
            this.Percentage = percentage;
            this.RecorDateTime = recorDateTime;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken percentageValue = inputObject["Percentage"];
                if (percentageValue != null && percentageValue.Type != JTokenType.Null)
                {
                    this.Percentage = ((string)percentageValue);
                }
                JToken recorDateTimeValue = inputObject["RecorDateTime"];
                if (recorDateTimeValue != null && recorDateTimeValue.Type != JTokenType.Null)
                {
                    this.RecorDateTime = ((DateTimeOffset)recorDateTimeValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Humidity
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Percentage == null)
            {
                throw new ArgumentNullException("Percentage");
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.Percentage != null)
            {
                outputObject["Percentage"] = this.Percentage;
            }
            outputObject["RecorDateTime"] = this.RecorDateTime;
            return outputObject;
        }
    }
}
