// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using WeatherServiceClientHW04.Models;

namespace WeatherServiceClientHW04.Models
{
    public static partial class HumidityCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Humidity> DeserializeJson(JToken inputObject)
        {
            IList<Humidity> deserializedObject = new List<Humidity>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Humidity humidity = new Humidity();
                humidity.DeserializeJson(iListValue);
                deserializedObject.Add(humidity);
            }
            return deserializedObject;
        }
    }
}
