// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WeatherServiceClientHW04.Models
{
    public partial class Pressure
    {
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _millibar;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Millibar
        {
            get { return this._millibar; }
            set { this._millibar = value; }
        }
        
        private DateTimeOffset _recorDateTime;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset RecorDateTime
        {
            get { return this._recorDateTime; }
            set { this._recorDateTime = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Pressure class.
        /// </summary>
        public Pressure()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the Pressure class with required
        /// arguments.
        /// </summary>
        public Pressure(string millibar, DateTimeOffset recorDateTime)
            : this()
        {
            if (millibar == null)
            {
                throw new ArgumentNullException("millibar");
            }
            this.Millibar = millibar;
            this.RecorDateTime = recorDateTime;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken millibarValue = inputObject["Millibar"];
                if (millibarValue != null && millibarValue.Type != JTokenType.Null)
                {
                    this.Millibar = ((string)millibarValue);
                }
                JToken recorDateTimeValue = inputObject["RecorDateTime"];
                if (recorDateTimeValue != null && recorDateTimeValue.Type != JTokenType.Null)
                {
                    this.RecorDateTime = ((DateTimeOffset)recorDateTimeValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Pressure
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Millibar == null)
            {
                throw new ArgumentNullException("Millibar");
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.Millibar != null)
            {
                outputObject["Millibar"] = this.Millibar;
            }
            outputObject["RecorDateTime"] = this.RecorDateTime;
            return outputObject;
        }
    }
}
