// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using WeatherServiceClientHW04.Models;

namespace WeatherServiceClientHW04.Models
{
    public static partial class TemperatureCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Temperature> DeserializeJson(JToken inputObject)
        {
            IList<Temperature> deserializedObject = new List<Temperature>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Temperature temperature = new Temperature();
                temperature.DeserializeJson(iListValue);
                deserializedObject.Add(temperature);
            }
            return deserializedObject;
        }
    }
}
