// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WeatherServiceClientHW04.Models
{
    public partial class Temperature
    {
        private string _degree;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Degree
        {
            get { return this._degree; }
            set { this._degree = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private DateTimeOffset _recorDateTime;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset RecorDateTime
        {
            get { return this._recorDateTime; }
            set { this._recorDateTime = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Temperature class.
        /// </summary>
        public Temperature()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the Temperature class with required
        /// arguments.
        /// </summary>
        public Temperature(string degree, DateTimeOffset recorDateTime)
            : this()
        {
            if (degree == null)
            {
                throw new ArgumentNullException("degree");
            }
            this.Degree = degree;
            this.RecorDateTime = recorDateTime;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken degreeValue = inputObject["Degree"];
                if (degreeValue != null && degreeValue.Type != JTokenType.Null)
                {
                    this.Degree = ((string)degreeValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken recorDateTimeValue = inputObject["RecorDateTime"];
                if (recorDateTimeValue != null && recorDateTimeValue.Type != JTokenType.Null)
                {
                    this.RecorDateTime = ((DateTimeOffset)recorDateTimeValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Temperature
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Degree == null)
            {
                throw new ArgumentNullException("Degree");
            }
            if (this.Degree != null)
            {
                outputObject["Degree"] = this.Degree;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            outputObject["RecorDateTime"] = this.RecorDateTime;
            return outputObject;
        }
    }
}
